<?php
	
	echo "<div class='terminosLegales'><h2>Términos legales</h2><p>La utilización de este web-site conlleva la aceptación y el pleno sometimiento por parte del Usuario de todas las Condiciones Generales de Uso vigentes en cada momento en que el Usuario acceda a este web-site, por lo que si éste no está de acuerdo con cualquiera de las condiciones aquí establecidas, no deberá usar esta página web.</p>";
	echo "<p>El Usuario se hace responsable de que su uso de este web-site sea conforme a la Ley, al presente Aviso Legal, Reglamentos e Instrucciones puestos en su conocimiento, así como la moral, las buenas costumbres y el orden público.</p>";
	echo "<p> De conformidad con lo dispuesto en el artículo 10 de la Ley 34/2002 de Servicios de la Sociedad de la Información (en adelante LSSICE), Mis Cositas, S.L.  le informa que es una sociedad limitada inscrita en el Registro Mercantil de Barcelona, Tomo 5194, Folio 34, Sección 8, Inscripción 1, Hoja BI-58003, y provista de CIF nº B95639423, con domicilio en Avenida Ramón y Cajal 39, CP 08223, Terrassa (España). Nuestra dirección de correo electrónico para contacto es info@misCositas.com.</p>";
	echo "<p>Mis Cositas S.L. es propietaria del nombre de dominio MISCOSITAS.COM , y de la página de Internet a la que se accede a través de dicho dominio.</p>";
	echo "<p> Los servicios de la sociedad de la información no pueden atentar contra los siguientes principios: el orden público, la seguridad, la salud pública y la defensa nacional; protección de los consumidores, respeto a la dignidad de la persona y no discriminación por motivos de raza, sexo, religión, opinión, nacionalidad, discapacidad o cualquier otra circunstancia personal o social; protección a la juventud y a la infancia. En defensa de estos principios y en cumplimiento de la citada LSSICE, Mis Cositas S.L. está obligada a colaborar con los órganos competentes que ordenen la interrupción del servicio o la retirada de determinados contenidos. Mis Cositas S.L. suspenderá la prestación de los servicios en cuanto tenga conocimiento efectivo de que la actividad o la información almacenada es ilícita o lesiona bienes y derechos de terceros, no siendo responsable de la información almacenada ni pudiendo exigirse responsabilidad de ningún tipo a Mis Cositas S.L. por la suspensión e interrupción del servicio.</p>";
	echo "<h2>1.-Propiedad Intelectual</h2>";
	echo "<p>Los Derechos de Propiedad Intelectual e Industrial sobre el sitio web conocido como www.miscositas.com pertenecen a Mis Cositas S.L. Los Derechos de Propiedad Intelectual sobre la página comprenden el contenido de la misma, su diseño con todos los elementos que lo integran y el código fuente con el que está programada, y están protegidos conforme a la Legislación Española e Internacional relativa a los Derechos de Autor.</p>";
	echo "<p>El Usuario puede utilizar el material que aparezca en este portal, única y exclusivamente, para su uso personal y privado, quedando prohibido su uso con fines comerciales o para incurrir en actividades ilícitas. Mis Cositas S.L. no confiere al Usuario ningún derecho de alteración, explotación, reproducción, distribución o comunicación pública sobre el mismo, reservándose Mis Cositas S.L. todos su derechos. La cesión de los citados derechos precisará el previo consentimiento por escrito por parte del titular de los mismos, de manera que el cliente no podrá poner a disposición de terceras personas dichos contenidos.</p>";
	echo "<p> La Propiedad Intelectual se extiende, además del contenido incluido en MISCOSITAS.COM, a sus gráficos, logotipos, diseños, imágenes y códigos fuente utilizados para su programación.</p>";
	echo "<p>Quedan excluídos del Derecho de Propiedad Intelectual del autor cualesquiera artículos o textos que aparezcan firmados por personas distintas del autor, cuya Propiedad Intelectual pertenece a los autores de los mismos, correspondiendo al autor el derecho a su utilización, reproducción o comunicación pública en la forma convenida con sus autores.</p>";
	echo "<p> Mis COsitas S.L. asume la obligación de velar tanto por el cumplimiento de todas las condiciones antes descritas como por la debida utilización de los contenidos ofrecidos en su web-site,  pudiendo ejercitar las acciones civiles y penales que le correspondieran en caso de infracción o incumplimiento de estos derechos por parte del Usuario.</p>";
	echo "<h2>2.- Responsabilidad</h2>";
	echo "<p>Mis Cositas S.L. no se hace responsable de las webs no propias mediante vínculos o enlaces (Links) o de cualquier contenido puesto a disposición de terceros. Cualquier uso de un vínculo o acceso a una web no propia será realizado por voluntad y a riesgo y ventura exclusiva del Usuario.</p>";
	echo "<p>Mis Cositas S.L. no recomienda ni garantiza ninguna de la información obtenida por o a través de un vínculo, ni se responsabiliza de ninguna pérdida, reclamación o perjuicio derivado del uso o mal uso de un vínculo, o de la información obtenida a través de él, incluyendo otros vínculos o webs, de la interrupción en el servicio o en el acceso, o del intento de usar o usar mal un vínculo, tanto al conectar a la web de MISCOSITAS.COM como al acceder a la información de otras webs desde la misma. Los riesgos derivados de la consulta de tales páginas corresponden exclusivamente al cliente que deberá regirse por los términos y condiciones de utilización de las mismas.</p>";
	echo "<p>Mis Coitas S.L. realiza las descripciones de todos los productos de la forma más concisa posible, incluyendo fotografías. Los precios, las características y la disponibilidad de los productos comercializados en esta web-site pueden variar sin previo aviso. Estos precios son válidos salvo error tipográfico.</p>";
	echo "<p>Mis Cositas S.L. se reserva el derecho de suspender, temporal o indefinidamente, el web-site MISCOSITAS.COM por el motivo que fuere. Mis Cositas S.L. no se hace responsable del incumplimiento de cualquier norma aplicable en que pueda incurrir el Usuario en su acceso al web-site www.misCositas.com y/o en el uso de las informaciones contenidos en el mismo.</p>";
	echo "<p> Cualquier producto puede ser retirado y/o modificado en cualquiera de sus aspectos (contenido, material, etc).</p>";
	echo "<p>Mis Cositas S.L. se reserva el derecho a rechazar la tramitación de un pedido por circunstancias excepcionales, y, en especial, la falta de autenticidad de los datos ofrecidos por el Usuario.</p>";
	echo "<p>Mis Cositas S.L. no se hace responsable del uso ilegítimo que terceras personas puedan hacer de los nombres de marca, nombres de producto, marcas comerciales que, no siendo propiedad de dicha entidad, aparezcan en el web-site www.factoriaderegalos.com.</p>";
	echo "<p>Mis Cositas S.L. no garantiza la ausencia de virus ni de otros elementos en el sitio web introducidos por terceros ajenos a Mis Cositas S.L. que puedan producir alteraciones en los sistemas físicos o lógicos de los Usuarios o en los documentos electrónicos y ficheros almacenados en sus sistemas. En consecuencia, Oparity Ekintza S.L. no será en ningún caso responsable de cualesquiera daños y perjuicios de toda naturaleza que pudieran derivarse de la presencia de virus u otros elementos que puedan producir alteraciones en los sistemas físicos o lógicos, documentos o ficheros de los Usuarios.</p>";
	echo "<p>En definitiva, el Usuario es el único responsable del uso que realice de los servicios, contenidos, enlaces (links) e hipertexto incluidos en el web-site www.miscositas.com</p>";
	echo "<h2>3.-Fuerza mayor</h2>";
	echo "<p> Las partes no incurrirán en responsabilidad ante cualquier falta debida a causa mayor. El cumplimiento de la obligación se demorará hasta el cese del caso de fuerza mayor.</p>";
	echo "<p> En todo caso, Mis Cositas S.L. no es responsable por incumplimiento o demora en el cumplimiento de alguna o todas las obligaciones derivadas de un contrato, cuya causa se base en actos, acontecimientos, falta de ejercicio, omisión o accidente, que escapan a nuestro control razonable.</p>";
	echo "<h3>POLÍTICA DE PRECIOS</h3>";
	echo "<p>Todos nuestros precios llevan el IVA incluido vigente en España, y están expresados en la moneda Euro.</p>";
	echo "<p> La empresa se reserva el derecho a revisar y, en su caso, modificar sin previo aviso los precios publicados si las condiciones lo requiriesen.</p></div>";
	
?>
